import = ["~/.config/alacritty/themes/themes/one_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
padding.x = 5
padding.y = 5
decorations = "Buttonless"
option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font"
size = 13

[keyboard]
bindings = [
  # opt + right and left jump between words
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]

[selection]
save_to_clipboard = true

[cursor]
style = "Beam"
unfocused_hollow = false
thickness = 0.2

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
