general.import = ["~/.config/alacritty/themes/themes/one_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
option_as_alt = "Both"

[font]
size = 14
normal.family = "FiraCode Nerd Font"
normal.style = "Regular"
bold.family = "FiraCode Nerd Font"
bold.style = "Bold"
italic.family = "FiraCode Nerd Font"
italic.style = "Italic"

[keyboard]
bindings = [
  # opt + right and left jump between words
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
  { key = "Slash", mods = "Control", chars = "\u001f" },
]

[selection]
save_to_clipboard = true

[cursor]
style = "Beam"
unfocused_hollow = false
thickness = 0.2

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[hints]
[[hints.enabled]]
# default
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"
command = "open"
mouse = { enabled = true, mods = "Shift" }

[[hints.enabled]]
# detect file paths
regex = "([^\\s:]+(?:/[^\\s:]+)+(?:\\:\\d+)?)"
command = "open"
mouse = { enabled = true, mods = "Shift" }
