brew "coreutils"
brew "gnu-sed"
brew "wget"

brew "asdf"
brew "neovim"
brew "starship"

brew "tmux"
brew "reattach-to-user-namespace"
brew "tmuxinator"

brew "bat"
brew "ctags"
brew "dust"
brew "git-delta"
brew "graphviz"
brew "lsd"
brew "fd"
brew "fzf"
brew "gh"
brew "hr"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "lazygit"
brew "ncdu"
brew "overmind"
brew "ripgrep"
brew "ruby-build"
brew "tealdeer"
brew "the_silver_searcher"
brew "yarn"
brew "zoxide"
brew "zsh-completions"

brew "cargo-nextest"
brew "cargo-watch"

brew "ffmpeg"
brew "vips"

tap "homebrew/cask-fonts"
cask "font-jetbrains-mono-nerd-font"
cask "font-fira-code-nerd-font"

tap "gjbae1212/gossm"
brew "gossm"
brew "awscli"
cask "aws-vault"

tap "1password/tap"
cask "1password-cli"

tap "espanso/espanso"
cask "espanso"

cask "git-credential-manager"
