require("user.core.options")
require("user.core.keymaps")
require("user.core.autocommands")

require("user.plugins")
require("user.plugins.treesitter")
require("user.plugins.comment")
require("user.plugins.nvim-tree")
require("user.plugins.lualine")
require("user.plugins.telescope")
require("user.plugins.vim-test")
require("user.plugins.bufferline")
require("user.plugins.nvim-cmp")
require("user.plugins.autopairs")
require("user.plugins.lsp.lsp-zero")
require("user.plugins.lsp.lsp_signature")
require("user.plugins.lsp.null-ls")
